version: '3'

services:
  app:
    build: .
    container_name: app
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
      - 8083:8080
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: db
    restart: always
    tty: true
    ports:
      - "5433:5432"
    volumes:
      - ./.docker/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: desafio

volumes:
  dbdata:
    external: true
